### ISSUE TITLE
feat: Support non-complicated x86_64 builds.

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/docker#17]
Post-merge feature after #14:

If we can find a way to give the `TARGETPLATFORM` build argument a default value of `linux/amd64`, we can make the build process simpler.

_From: https://github.com/dogecoin/docker/pull/14#r754617790_

**Comment by AbcSxyZ** [comment]
The idea is to detect the architecture inside the Dockerfile, right ? Not to enable the user to use `--build-arg` with some trick ?

Possibly `dpkg` or `uname` may do the job. I would love to see output of the following commands:
 - `dpkg --print-architecture`
 - `dpkg-architecture --query DEB_BUILD_GNU_TYPE`
 - `dpkg-architecture --query DEB_BUILD_MULTIARCH`
 - `dpkg-architecture --query DEB_BUILD_ARCH`
 - `uname -m`
 
 For architectures `amd64`, `arm64`, `armv7` & `i386`.
 
 | Architecture | --print-architecture | DEB_BUILD_GNU_TYPE | DEB_BUILD_MULTIARCH | DEB_BUILD_ARCH | uname -m |
|--------------|---------------------------|--------------------|---------------------|----------------|------------------------|
| amd64        | amd64                 | x86_64-linux-gnu | x86_64-linux-gnu | amd64   | x86_64  |
| arm64        |  arm64 |  aarch64-linux-gnu  | aarch64-linux-gnu |  arm64  |  aarch64 |
| armv7        |  armhf  |   arm-linux-gnueabihf   | arm-linux-gnueabihf  | armhf | armv7l  |
| i386         |  i386  | i686-linux-gnu | i386-linux-gnu | i386  | x86_64  |
 
Not sure how I can get other value, **if anyone has any missing arch and can share some outputs**, I will also try to investigate with Docker and Internet if I could find it.

Idk if there are any other commands who can retrieve architecture, if someone has a suggestion.

**Edit:** Add `uname -m` as commands to test.

**Edit 2:** Add all architectures, by printing commands when building images with `qemu`/`buildx`. See outputs in [GitHub Action logs](https://github.com/AbcSxyZ/git-testing/actions/runs/1513332312).

**Comment by AbcSxyZ** [comment]
With the research result, what comes to my mind is using `dpkg --print-architecture` and doing something like that:

```Dockerfile
RUN set -ex && TARGETPLATFORM=$(dpkg --print-architecture) && \
    if [ "${TARGETPLATFORM}" = "amd64" ]; then TARGETPLATFORM=x86_64-linux-gnu; fi \
    && if [ "${TARGETPLATFORM}" = "arm64" ]; then TARGETPLATFORM=aarch64-linux-gnu; fi \
    && if [ "${TARGETPLATFORM}" = "armhf" ]; then TARGETPLATFORM=arm-linux-gnueabihf; fi \
    && if [ "${TARGETPLATFORM}" = "i386" ]; then TARGETPLATFORM=i686-pc-linux-gnu; fi \
    && wget https://github.com/dogecoin/dogecoin/releases/download/v${VERSION}/dogecoin-${VERSION}-${TARGETPLATFORM}.tar.gz
 ```
 
 We're having cross architecture build without `buildx` dependency :)
 
 **Edit:** I installed `dpkg-dev`, but maybe it's not even needed, I'm verifying ! **[It's working, removing dependency]**
