### ISSUE TITLE
apt add `--no-install-recommends` flags

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/docker#21]
Reduce downloaded/installed size of `apt` packages by adding `--no-install-recommends`.

**Comment by patricklodder** [comment]
On its own, this saves 2MB in the final image on my test runs. I'll PR this, but took a quick look and we can optimize elsewhere too. I'll create a separate issue for that.

**Comment by AbcSxyZ** [comment]
Fixed with https://github.com/dogecoin/docker/pull/41
