### ISSUE TITLE
Dynamic version build using dynamic hash verification

### ISSUE THREAD

**Issue by AbcSxyZ** [dogecoin/docker#5]
Following comments from seed PR https://github.com/dogecoin/dogecoin/pull/2337#discussion_r726592096.

In the current situation, it's possible to build a single version with each Dockerfile because the hash of Dogecoin Core is hardcoded
within the Dockerfile.

By taking a look at [Docker security instruction to build Dockerfile](https://github.com/docker-library/official-images#security), they are suggesting alternatives to avoid this hardcoded hash.

Need extra investigation, I will share my finding about the topic here to see if an improvement is possible.

**Comment by patricklodder** [comment]
Would it help if we put a process on this repo that checks version / arch / checksum against contents of gitian.sigs? That should be relatively easy to do with GH Actions.

**Comment by xanimo** [comment]
I think dynamically verifying from gitian.sigs is a great idea.

**Comment by patricklodder** [comment]
I have implemented the Gitian verification in the Dockerfile in #6, to demonstrate what that would look like.
